### ISSUE TITLE
change encoder to Nayuki engine 

### ISSUE THREAD

**Issue by ErwanMAS** [six-two/qr.html#5]
https://github.com/nayuki/QR-Code-generator

You can try difference for these strings between https://www.nayuki.io/page/qr-code-generator-library and your page

VERSION1VERSION2VERSION3V

12345678901234567890123456789012345678901

The reason is that encoding will depend of the data ( see https://en.wikipedia.org/wiki/QR_code#Information_capacity )

**Comment by six-two** [comment]
Thanks for the suggestion, I will look into it.

One drawback that I see is that the library is much bigger (around 44kb, source: https://github.com/nayuki/QR-Code-generator/releases). But that is unminified, maybe I can get it a bit smaller.

**Comment by six-two** [comment]
The Nayuki library is indeed better at encoding certain payloads and can be shrunken down to a reasonable size by minifying it. I changed it to be the library for the `qr.html` page, while also creating a copy with the old library (`qr-legacy.html`) in case someone liked the old library better. Since Nayuki is slightly bigger, `tiny-qr.html` will keep using the old library.
